### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ctxis/RDP-Replay#1]
I would like to point out that identifiers like "[`__pcap_delay_h__`](https://github.com/ctxis/RDP-Replay/blob/25e20be46d58fd079b4c5a1cdfef76d807304ce8/tools/pcap_delay.h#L17)" and "[`__ssl_decrypt_h__`](https://github.com/ctxis/RDP-Replay/blob/25e20be46d58fd079b4c5a1cdfef76d807304ce8/tools/ssl_decrypt.h#L17)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by SteveWare** [comment]
Fixed

**Comment by elfring** [comment]
I recommend to [take another look at your identifier selection](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?").

**Comment by SteveWare** [comment]
This should now be done.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/ctxis/RDP-Replay/commit/64f112b1643df353bbe3a22fbc34a469df0d7fd1 "Deletion of a few underscores").
