### ISSUE TITLE
Possible to build it for Windows?

### ISSUE THREAD

**Issue by maaaaz** [ctxis/RDP-Replay#5]
Hello,

Do you think that it would be possible to compile it for Windows, under cygwin or VS ?
Anyway, thank you for that awesome tool.

Cheers!

**Comment by SteveWare** [comment]
There are no plans for a Windows version.  There are still options for you on Windows. Microsoft are working on [this](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/), but a more straight forward approach may be to install Ubuntu on a VM. This should then just work as is.

**Comment by maaaaz** [comment]
Okay !
